version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./frontend/build:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 3000:80

  backend:
    working_dir: /var/www
    image: node:12
    volumes:
      - ./backend:/var/www
    ports:
      - 3080:3000
    links:
      - db
    depends_on:
      - db
    command: node ./node_modules/ts-node/dist/bin.js ./src/index.ts

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: med_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 7433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
